### ISSUE TITLE
join is undefined error

### ISSUE THREAD

**Issue by Danny-Engelman** [hqjs/vscode-hq-live-server#11]
I occasionaly get:

````
Cannot read property 'join' of undefined
TypeError: Cannot read property 'join' of undefined
    at file:///c:/Users/XXX/.vscode/extensions/hqjs.hq-live-server-0.0.11/node_modules/@hqjs/hq/compilers/html.mjs:138:42
    at c:\Users\XXX\.vscode\extensions\hqjs.hq-live-server-0.0.11\node_modules\posthtml\lib\api.js:91:45
````

Line 138 is:
![](https://i.imgur.com/UtVpbgN.png)

and rebooting is a drastic solution

**Comment by hqjs** [comment]
Thanks for reporting, I expected style content to be at least empty string. I'll prepare a patch.
